### ISSUE TITLE
Search map for component

### ISSUE THREAD

**Issue by rp41-txst** [txstate-etc/integration-map#10]
Is there a way to search the map for a component that needs to be updated? It's a little challenging to find the system you are looking for if you don't know what other systems it is connected to.

**Comment by ajthyng** [comment]
I added a search

I wanted to have the nodes highlight a bit better but I can't change the icon color, the shapes are actually very limited.

**Comment by rp41-txst** [comment]
Understandable. Thanks for checking into the possibilities. I'll look at search this evening.

Regards,

Rori Parks Sheffield
Director, Mobile/Web Systems
Technology Resources
Texas State University
JCK 726
512.245.1388

~We can do more together than we could ever do alone. (B.Haley; We Are 1 Movement)~
________________________________
