### ISSUE TITLE
Map scale reset

### ISSUE THREAD

**Issue by rp41-txst** [txstate-etc/integration-map#11]
Every time I edit an existing object on the map the scale resets. For a little more detail, I start off zoomed in to the item, but after I edit, save and click to go back to the map, the map refreshes, and the scale is itty-bity (e.g. - (I can't read any of the names). Is there any way to alter this behavior?

**Comment by ajthyng** [comment]
i could make the graph focus on the thing you just added if that would be helpful

i'm currently redrawing the whole graph when you add a node, which is not ideal and i want to fix, but that's a good bit of effort to do.

**Comment by rp41-txst** [comment]
I think having the map refocus on the node you just entered is a great solution, especially for the time being.

Regards,

Rori Parks Sheffield
Director, Mobile/Web Systems
Technology Resources
Texas State University
JCK 726
512.245.1388

~We can do more together than we could ever do alone. (B.Haley; We Are 1 Movement)~
________________________________

**Comment by rp41-txst** [comment]
The changes you made to the zoom behavior make the animation much less drastic. I don't think we need to do anything more for now.
