### ISSUE TITLE
Non-system objects

### ISSUE THREAD

**Issue by rp41-txst** [txstate-etc/integration-map#12]
Do we need a non-system object icon for the connector points for the .NET systems (one-way integrations, two-way integrations, and no integrations)?

**Comment by rp41-txst** [comment]
Right now, I have a placeholder for these objects. I'm using the internal system container (square).

**Comment by rp41-txst** [comment]
Oh yeah, if we choose to connect these systems to a non-system object, should we also have a connector that does not have a read/write attribute (i.e. - a totally new map item)?

**Comment by ajthyng** [comment]
its technically an undirected graph (now) 
so we can make the connections mean whatever we want

it seems like it would be good to make the distinction that those systems are either connected to nothing (now possible since you can position them independently)

**Comment by rp41-txst** [comment]
Ok. I'll look at how to do that tonight. I may need your feedback on what makes most sense when we meet tomorrow.

Regards,

Rori Parks Sheffield
Director, Mobile/Web Systems
Technology Resources
Texas State University
JCK 726
512.245.1388

~We can do more together than we could ever do alone. (B.Haley; We Are 1 Movement)~
________________________________

**Comment by rp41-txst** [comment]
This is no longer an issue. We are going to use free-standing text, which is being tracked as a separate issue/request.
